version: '3'
services:
  service-a:
    build:
      context: ./service-a
    ports:
      - '3001:3000'

  service-b:
    build:
      context: ./service-b
    ports:
      - '3002:3000'

  service-c:
    build:
      context: ./service-c
    ports:
      - '3003:3000'

  mongo:
    image: mongo
    ports:
      - '27017:27017'